version: '2'

services:

  jenkins:
    dockerfile: ./Dockerfile
    context: .
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - my-jenkins-network

networks:
  my-jenkins-network:
    driver: bridge
